USE [LITS]
GO

/****** Object:  Table [dbo].[pl_customer_information]    Script Date: 10/24/2019 1:52:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[pl_customer_information](
	[pk_id] [int] IDENTITY(1,1) NOT NULL,
	[fk_application_information_id] [int] NULL,
	[fk_customer_information_id] [int] NULL,
	[fk_pl_application_information_id] [int] NULL,
	[fk_m_borrower_type_id] [int] NULL,
	[created_date] [datetime] NULL,
	[created_by] [nvarchar](50) NULL,
	[is_active] [bit] NULL,
	[remark] [nvarchar](2000) NULL,
	[fk_type_id] [int] NOT NULL,
	[fk_status_id] [int] NULL,
	[update_date] [datetime] NULL,
	[update_by] [nvarchar](50) NULL,
	[fk_bank_relationship_id] [int] NULL,
	[fk_customer_segment_id] [int] NULL,
	[fk_initital_id] [int] NULL,
	[full_name] [nvarchar](500) NULL,
	[embossing_name] [nvarchar](128) NULL,
	[dob] [datetime] NULL,
	[fk_gender_id] [int] NULL,
	[fk_nationality_id] [int] NULL,
	[fk_marital_status_id] [int] NULL,
	[permanent_address] [nvarchar](500) NULL,
	[permanent_ward] [nvarchar](50) NULL,
	[permanent_district] [nvarchar](500) NULL,
	[fk_permanent_city_id] [int] NULL,
	[fk_permanent_address_type_id] [int] NULL,
	[fk_residential_address] [int] NULL,
	[residential_address] [nvarchar](500) NULL,
	[residential_ward] [nvarchar](500) NULL,
	[residential_district] [nvarchar](500) NULL,
	[fk_residential_city_id] [int] NULL,
	[issued_date_residential_address] [datetime] NULL,
	[owner_residential_address] [nvarchar](500) NULL,
	[primary_phone_no] [nvarchar](50) NULL,
	[home_phone_no] [nvarchar](50) NULL,
	[billing_address] [nvarchar](500) NULL,
	[email_address_1] [nvarchar](50) NULL,
	[email_address_2] [nvarchar](50) NULL,
	[email_address_3] [nvarchar](50) NULL,
	[fk_current_position_id] [int] NULL,
	[fk_verified_position_id] [int] NULL,
	[fk_occupation_id] [int] NULL,
	[fk_occupation_verified_id] [int] NULL,
	[fk_occupation_type_id] [int] NULL,
	[fk_occupation_type_verified_id] [int] NULL,
	[fk_contract_type_id] [int] NULL,
	[is_pass_probation] [bit] NULL,
	[fk_operation_self_employed_id] [int] NULL,
	[fk_payment_type_id] [int] NULL,
	[fk_business_nature_code_id] [int] NULL,
	[fk_current_resident_type_code_id] [int] NULL,
	[fk_ownership_type_code_id] [int] NULL,
	[fk_customer_type_code_id] [nvarchar](20) NULL,
	[years_in_current_employment_id] [int] NULL,
	[residence_name] [nvarchar](500) NULL,
	[time_current_address] [int] NULL,
	[fk_education_id] [int] NULL,
	[number_nank_relationship] [int] NULL,
	[number_bank_queries] [int] NULL,
	[fk_trading_area_id] [int] NULL,
	[contract_start] [datetime] NULL,
	[contract_length] [int] NULL,
	[fk_watch_list_status_id] [int] NULL,
	[fk_resident_status_id] [int] NULL,
	[place_of_birth] [nvarchar](500) NULL,
	[office_email] [nvarchar](50) NULL,
	[fk_qualifications_id] [int] NULL,
	[social_insurance_number] [nvarchar](50) NULL,
	[third_party_contact_1] [nvarchar](500) NULL,
	[third_party_contact_2] [nvarchar](250) NULL,
	[is_si_checking] [bit] NULL,
	[fk_billing_address_id] [int] NULL,
	[fk_residential_district_id] [int] NULL,
	[fk_permanent_district_id] [int] NULL,
	[fk_address_proof_type_id] [int] NULL,
	[fk_zone_classification_id] [int] NULL,
	[fk_verification_email_status_id] [int] NULL,
	[expired_date_residential_card] [datetime] NULL,
	[fk_trading_area_verified_id] [int] NULL,
	[fk_prohibited_and_resstricted_lending_id] [int] NULL,
	[prohibited_and_resstricted_lending_list] [nvarchar](2000) NULL,
	[fk_source_email_domain_id] [int] NULL,
	[is_email_verification] [bit] NULL,
	[referee_mobile_phone_1] [nvarchar](50) NULL,
	[referee_mobile_phone_2] [nvarchar](50) NULL,
 CONSTRAINT [PK_pl_customer_information] PRIMARY KEY CLUSTERED 
(
	[pk_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


